version = "1.0"

[main]
name = "Trilium configuration"
services = ["__APP__"]

    [main.config]
    name = "Configuration Options"

        [main.config.instance_name]
        ask = "Set Instance name"
        type = "string"
        help = "Choose a unique name for this instance"
        bind = "instanceName:__FINALPATH__/config.ini"
