test_format = 1.0

[default]

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.85a53b5.name = "Merge pull request #36 from YunoHost-Apps/testing"
